version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: gpu_console
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    env_file:
      - backend/.env
    depends_on:
      - db
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    restart: always
    env_file:
      - frontend/.env
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  db_data:
